name: Docker-exp-auto-pull

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Upload ssh-key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_HOST_KEY }}" > ../private
          sudo chmod 600 ../private
          
      - name: Connect with ssh
        run: |
          ssh -i ~/.ssh/private root@89.223.125.17
          ls
          exit
          
